receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4320
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ logging ]
    traces:
      receivers: [ otlp ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      exporters: [ logging ]
